finance/urls.py
from django.urls import path

from user.decorators import finance_required
from . import views

urlpatterns = [
    path('confirm_order_payment/<int:order_id>/', finance_required(views.confirm_order_payment),
         name="confirm_order_payment"),
    path('confirm_booking_payment/<int:booking_id>/', finance_required(views.confirm_booking_payment),
         name="confirm_booking_payment"),
    path('confirm_training_payment/<int:slug>/', finance_required(views.confirm_training_payment),
         name="confirm_training_payment"),
    path('search/', finance_required(views.search), name="search"),
    path('feedback/', finance_required(views.feedback), name="feedback"),
    path('password/', finance_required(views.password_change), name="password_change"),
    path('faq/', finance_required(views.faq), name="faq"),
    path('profile/', finance_required(views.profile_main), name="profile_main"),
    path('booking_payment/', finance_required(views.BookingPaymentListView.as_view()),
         name="booking_payment"),
    path('pending_booking_payment/', finance_required(views.PendingBookingPaymentListView.as_view()),
         name="pending_booking_payment"),
    path('order_payment/', finance_required(views.OrderPaymentListView.as_view()), name="order_payment"),
    path('pending_order_payment/', finance_required(views.PendingOrderPaymentListView.as_view()),
         name="pending_order_payment"),
    path('pending_payment/', finance_required(views.PendingTrainingPaymentListView.as_view()), name="pending_payment"),
    path('payment/', finance_required(views.TrainingPaymentListView.as_view()), name="payment"),
    path('login/', views.login, name="login"),
    path('register/', views.FinanceSignUpView.as_view(), name="register"),
    path('verify/<uidb64>/<token>/', views.VerifyEmail.as_view(), name='verify'),
    path('', finance_required(views.Home.as_view()), name="index"),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('search/', views.search, name="search"),
    path('term_condition/', views.term_condition, name="term_condition"),
    path('privacy-policy/', views.privacy_policy, name="privacy_policy"),
    path('about-us/', views.about_us, name="about-us"),
    path('salonists/', views.Salonists.as_view(), name="salonists"),
    path('', views.Home.as_view(), name="index"),
]

manager/urls.py
from django.urls import path

from user.decorators import manager_required
from . import views

urlpatterns = [
    path('add_training/', manager_required(views.TrainingCreateView.as_view()), name="add_training"),
    path('confirm_training_application/<int:application_id>/', manager_required(views.confirm_training_application),
         name="confirm_training_application"),
    path('approved_training_application_pdf/', manager_required(views.approved_training_application_pdf),
         name="approved_training_application_pdf"),
    path('pending_training_application_pdf/', manager_required(views.pending_training_application_pdf),
         name="pending_training_application_pdf"),
    path('pending_training_pdf/', manager_required(views.pending_training_pdf), name="pending_training_pdf"),
    path('training_pdf/', manager_required(views.training_pdf), name="training_pdf"),
    path('salonists_pdf/', manager_required(views.salonists_pdf), name="salonists_pdf"),
    path('products_pdf/', manager_required(views.products_pdf), name="products_pdf"),
    path('manager_training_application/', manager_required(views.ApprovedTrainingApplicationListView.as_view()),
         name="manager_training_application"),
    path('manager_pending_training_application/', manager_required(views.PendingTrainingApplicationListView.as_view()),
         name="manager_pending_training_application"),
    path('manager_training/', manager_required(views.TrainingListView.as_view()), name="manager_training"),
    path('manager_pending/', manager_required(views.PendingTrainingListView.as_view()),
         name="pending_manager_training"),
    path('search/', manager_required(views.search), name="search"),
    path('feedback/', manager_required(views.feedback), name="feedback"),
    path('password/', manager_required(views.password_change), name="password_change"),
    path('faq/', manager_required(views.faq), name="faq"),
    path('profile/', manager_required(views.profile_main), name="profile_main"),
    path('create_salonist_service/', manager_required(views.SalonistServiceCreateView.as_view()),
         name="create_salonist_service"),
    path('salonist_service_list/', manager_required(views.SalonistServiceListView.as_view()),
         name="salonist_service_list"),
    path('apprenticeships/', manager_required(views.ApprenticeshipListView.as_view()), name="apprenticeships"),
    path('create-apprenticeship/', manager_required(views.ApprenticeshipCreateView.as_view()),
         name="create_apprenticeship"),
    path('create-salonist/', manager_required(views.SalonistCreateView.as_view()), name="create_salonist"),
    path('create-product/', manager_required(views.ProductCreateView.as_view()), name="create_product"),
    path('create-service/', manager_required(views.ServiceCreateView.as_view()), name="create_service"),
    path('services/', manager_required(views.ServicesListView.as_view()), name="services"),
    path('products/', manager_required(views.ProductsListView.as_view()), name="products"),
    path('salonists/', manager_required(views.SalonistsListView.as_view()), name="salonists"),
    path('customers/', manager_required(views.CustomersListView.as_view()), name="customers"),
    path('login/', views.login, name="login"),
    path('register/', views.ManagerSignUpView.as_view(), name="register"),
    path('verify/<uidb64>/<token>/', views.VerifyEmail.as_view(), name='verify'),
    path('', manager_required(views.Home.as_view()), name="index"),
]

salon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name="user/forgot-password.html",
             html_email_template_name="user/email/password-reset.html",
             subject_template_name="user/email/password_reset_subject.txt",
         ),
         name="password_reset"),
    path('reset_password_done/',
         auth_views.PasswordResetDoneView.as_view(template_name="user/password-reset-done.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="user/auth-reset-password.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name="user/password-reset-complete.html"),
         name="password_reset_complete"),
    # ============================== Password Reset urls end ===========================================
    # third party app
    # path('mpesa/', include('mpesa_api.core.urls', 'mpesa')),

    path('admin/', admin.site.urls),
    path('finance/', include(('finance.urls', 'finance'), namespace="finance")),
    path('manager/', include(('manager.urls', 'manager'), namespace="project_manager")),
    path('salonist/', include(('salonist.urls', 'salonist'), namespace="salonist")),
    path('customer/', include(('customer.urls', 'customer'), namespace="customer")),
    path('trainee/', include(('trainee.urls', 'trainee'), namespace="trainee")),
    path('shipment/', include(('shipment.urls', 'shipment'), namespace="shipment")),
    path('stock/', include(('stock.urls', 'stock'), namespace="stock")),
    path('', include(('home.urls', 'home'), namespace="home")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'manager.views.error_404'
handler500 = 'manager.views.error_500'
handler403 = 'manager.views.error_403'
handler400 = 'manager.views.error_503'

manager/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from user.models import CustomUser, Profile, Feedback


class Manager(CustomUser):
    pass

    class Meta:
        verbose_name = ' Manager'
        verbose_name_plural = ' Managers'


class ManagerProfile(Profile):
    user = models.OneToOneField(Manager, on_delete=models.CASCADE)

    class Meta:
        verbose_name = ' Manager Profile'
        verbose_name_plural = ' Managers Profile'


class ManagerFeedback(Feedback):
    user = models.ForeignKey(Manager, on_delete=models.CASCADE)

    class Meta:
        verbose_name = ' Manager'
        verbose_name_plural = ' Manager Feedback'


@receiver(post_save, sender=Manager)
def manager_profile(sender, instance, created, **kwargs):
    if created:
        ManagerProfile.objects.create(user=instance)
        instance.managerprofile.save()

manager/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from .models import Manager, ManagerProfile, Feedback, ManagerFeedback


class ManagerSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Manager
        fields = ['last_name', 'first_name', 'email']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_manager = True
        user.is_active = False
        if commit:
            user.save()
        return user


class ManagerProfileForm(ModelForm):
    class Meta:
        model = ManagerProfile
        fields = ['image', 'gender', 'phone_number']


class ManagerForm(ModelForm):
    class Meta:
        model = Manager
        fields = ['last_name', 'first_name', 'email']


class ManagerFeedbackForm(ModelForm):
    class Meta:
        model = ManagerFeedback
        fields = ['subject', 'message']

manager/templates/manager/tables/apprenticeship-list.html
{% extends 'manager/layout/base.html' %}
{% load static %}
{% block title %}Apprenticeship List{% endblock title %}
{% include 'manager/includes/data-table-styles.html' %}
{% include 'manager/includes/header.html' %}
{% include 'manager/includes/sidebar.html' %}
{% block content %}

	<!-- Page Wrapper -->
	<div class="page-wrapper">
		<div class="content container-fluid">

			<!-- Page Header -->
			<div class="page-header">
				<div class="row">
					<div class="col-sm-12">
						<h3 class="page-title">List of Apprenticeship</h3>
						<ul class="breadcrumb">
							<li class="breadcrumb-item"><a href="{% url 'manager:index' %}">Dashboard</a></li>
							<li class="breadcrumb-item"><a href="javascript:(0);">Apprenticeship</a></li>
							<li class="breadcrumb-item active">Apprenticeship</li>
						</ul>
					</div>
				</div>
			</div>
			<!-- /Page Header -->

			<div class="row">
				<div class="col-sm-12">
					<div class="card">
						<div class="card-body">
							<div class="table-responsive">
								<div class="table-responsive">
								<table class="datatable table table-hover table-center mb-0">
									<thead>
										<tr>
											<th>#</th>
											<th>Salonist</th>
											<th>Date</th>
											<th>Created</th>
										</tr>
									</thead>
									<tbody>
										{% for object in object_list %}
										<tr>
											<td>{{forloop.counter}}</td>
											<td>
												<h2 class="table-avatar">
													<a href="#" class="avatar avatar-sm mr-2"><img class="avatar-img" src="{{object.salonist.salonistprofile.image.url}}" alt="{{object.salonist.get_full_name}}"></a>
													<a href="#">{{object.salonist.get_full_name}}</a>
												</h2>
											</td>
											<td>{{object.date}}</td>
											<td>{{object.created}}</td>
										</tr>
										{% endfor %}
									</tbody>
								</table>
							</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
	<!-- /Page Wrapper -->

{% endblock content %}
{% include 'manager/includes/data-table-scripts.html' %}

manager/templates/manager/tables/approved-training-application-list.html
{% extends 'manager/layout/base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Trainings List{% endblock title %}
{% include 'manager/includes/data-table-styles.html' %}
{% include 'manager/includes/header.html' %}
{% include 'manager/includes/sidebar.html' %}
{% block content %}

	<!-- Page Wrapper -->
	<div class="page-wrapper">
		<div class="content container-fluid">

			<!-- Page Header -->
			<div class="page-header">
				<div class="row">
					<div class="col-sm-12">
						<h3 class="page-title">List of Training Applications <a href="{% url 'manager:approved_training_application_pdf' %}" class="text-align-right" style="text-align: right;"> <i class="fe fe-print"> Generate pdf</i></a></h3>
						<ul class="breadcrumb">
							<li class="breadcrumb-item"><a href="{% url 'manager:index' %}">Dashboard</a></li>
							<li class="breadcrumb-item"><a href="javascript:(0);">Training Applications</a></li>
							<li class="breadcrumb-item active">Training Applications</li>
						</ul>
					</div>
				</div>
			</div>
			<!-- /Page Header -->

			<div class="row">
				<div class="col-sm-12">
					<div class="card">
						<div class="card-body">
							<div class="table-responsive">
								<div class="table-responsive">
								<table class="datatable table table-hover table-center mb-0">
									<thead>
										<tr>
											<th>#</th>
											<th>code</th>
											<th>service</th>
											<th>salonist</th>
											<th>Trainee</th>
											<th>price</th>
											<th>start date</th>
											<th>end date</th>
											<th>status</th>
										</tr>
									</thead>
									<tbody>
										{% for object in object_list %}
										<tr>
											<td>{{forloop.counter}}</td>
											<td>{{object.code}}</td>
											<td>{{object.training.service.name}}</td>
											<td>{{object.training.salonist.get_full_name}}</td>
											<td>{{object.trainee.get_full_name}}</td>
											<td>Ksh {{object.training.price|floatformat:2|intcomma}}</td>
											<td>{{object.training.date}}</td>
											<td>{{object.training.end_date}}</td>
											<td>
												{% if object.is_approved %}
													Approved
												{% else %}
													Pending
												{% endif %}
											</td>
										</tr>
										{% endfor %}
									</tbody>
								</table>
							</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- /Page Wrapper -->

{% endblock content %}
{% include 'manager/includes/data-table-scripts.html' %}

manager/templates/manager/tables/customers-list.html
{% extends 'manager/layout/base.html' %}
{% load static %}
{% block title %}Customers List{% endblock title %}
{% include 'manager/includes/data-table-styles.html' %}
{% include 'manager/includes/header.html' %}
{% include 'manager/includes/sidebar.html' %}
{% block content %}

	<!-- Page Wrapper -->
	<div class="page-wrapper">
		<div class="content container-fluid">

			<!-- Page Header -->
			<div class="page-header">
				<div class="row">
					<div class="col-sm-12">
						<h3 class="page-title">List of Customers</h3>
						<ul class="breadcrumb">
							<li class="breadcrumb-item"><a href="{% url 'manager:index' %}">Dashboard</a></li>
							<li class="breadcrumb-item"><a href="javascript:(0);">Users</a></li>
							<li class="breadcrumb-item active">Customer</li>
						</ul>
					</div>
				</div>
			</div>
			<!-- /Page Header -->

			<div class="row">
				<div class="col-sm-12">
					<div class="card">
						<div class="card-body">
							<div class="table-responsive">
								<div class="table-responsive">
								<table class="datatable table table-hover table-center mb-0">
									<thead>
										<tr>
											<th>#</th>
											<th>Customer Name</th>
											<th>Email</th>
											<th>Phone</th>
											<th>Status</th>
											<th>Date</th>
										</tr>
									</thead>
									<tbody>
										{% for object in object_list %}
										<tr>
											<td>{{forloop.counter}}</td>
											<td>
												<h2 class="table-avatar">
													<a href="#" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="{{object.customerprofile.image.url}}" alt="{{object.get_full_name}}"></a>
													<a href="#">{{object.get_full_name}}</a>
												</h2>
											</td>
											<td>{{object.email}}</td>
											<td>{{object.customerprofile.phone_number}}</td>
											<td>
												{% if object.is_active and not object.is_archived and object.is_verified %}
												Active
												{% elif object.is_active and object.is_archived and object.is_verified %}
												Archived
												{% elif object.is_active and not object.is_archived and not object.is_verified %}
												Unverified
												{% endif %}
											</td>
											<td>{{object.created}}</td>
										</tr>
										{% endfor %}
									</tbody>
								</table>
							</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
	<!-- /Page Wrapper -->

{% endblock content %}
{% include 'manager/includes/data-table-scripts.html' %}

manager/templates/manager/tables/pending-training-application-list.html
{% extends 'manager/layout/base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Trainings List{% endblock title %}
{% include 'manager/includes/data-table-styles.html' %}
{% include 'manager/includes/header.html' %}
{% include 'manager/includes/sidebar.html' %}
{% block content %}

	<!-- Page Wrapper -->
	<div class="page-wrapper">
		<div class="content container-fluid">

			<!-- Page Header -->
			<div class="page-header">
				<div class="row">
					<div class="col-sm-12">
						<h3 class="page-title">List of Pending Trainings <a href="{% url 'manager:pending_training_application_pdf' %}" class="text-align-right" style="text-align: right;"> <i class="fe fe-print"> Generate pdf</i></a></h3>
						<ul class="breadcrumb">
							<li class="breadcrumb-item"><a href="{% url 'manager:index' %}">Dashboard</a></li>
							<li class="breadcrumb-item"><a href="javascript:(0);">Pending Training</a></li>
							<li class="breadcrumb-item active">Pending Training</li>
						</ul>
					</div>
				</div>
			</div>
			<!-- /Page Header -->

			<div class="row">
				<div class="col-sm-12">
					<div class="card">
						<div class="card-body">
							<div class="table-responsive">
								<div class="table-responsive">
								<table class="datatable table table-hover table-center mb-0">
									<thead>
										<tr>
											<th>#</th>
											<th>code</th>
											<th>service</th>
											<th>salonist</th>
											<th>Trainee</th>
											<th>price</th>
											<th>start date</th>
											<th>end date</th>
											<th>status</th>
											<th class="text-right">Action</th>
										</tr>
									</thead>
									<tbody>
										{% for object in object_list %}
										<tr>
											<td>{{forloop.counter}}</td>
											<td>{{object.code}}</td>
											<td>{{object.training.service.name}}</td>
											<td>{{object.training.salonist.get_full_name}}</td>
											<td>{{object.trainee.get_full_name}}</td>
											<td>Ksh {{object.training.price|floatformat:2|intcomma}}</td>
											<td>{{object.training.date}}</td>
											<td>{{object.training.end_date}}</td>
											<td>
												{% if object.is_approved %}
													Approved
												{% else %}
													Pending
												{% endif %}
											</td>
											<td class="text-right">
												<div class="table-action">
														<button class="btn btn-sm bg-info-light confirm" id="{{object.id}}"
																data-url="{% url 'manager:confirm_training_application' application_id=object.id %}"
																data-slug="{{object.id}}">
															<i class="fe fe-check"></i> Approve
														</button>
<!--													<a href="#" class="btn btn-sm bg-primary-light">-->
<!--														<i class="fe fe-print"></i> Print-->
<!--													</a>-->
												</div>
											</td>
										</tr>
										{% endfor %}
									</tbody>
								</table>
							</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- /Page Wrapper -->

{% endblock content %}
{% include 'manager/includes/data-table-scripts.html' %}
{% block scripts %}
	<script src="{% static 'finance/confirm-order-payment.js' %}"></script>
{% endblock %}

manager/templates/manager/tables/pending-training-list.html
{% extends 'manager/layout/base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Trainings List{% endblock title %}
{% include 'manager/includes/data-table-styles.html' %}
{% include 'manager/includes/header.html' %}
{% include 'manager/includes/sidebar.html' %}
{% block content %}

	<!-- Page Wrapper -->
	<div class="page-wrapper">
		<div class="content container-fluid">

			<!-- Page Header -->
			<div class="page-header">
				<div class="row">
					<div class="col-sm-12">
						<h3 class="page-title">List of Pending Trainings <a href="{% url 'manager:pending_training_pdf' %}" class="text-align-right" style="text-align: right;"> <i class="fe fe-print"> Generate pdf</i></a></h3>
						<ul class="breadcrumb">
							<li class="breadcrumb-item"><a href="{% url 'manager:index' %}">Dashboard</a></li>
							<li class="breadcrumb-item"><a href="javascript:(0);">Pending Training</a></li>
							<li class="breadcrumb-item active">Pending Training</li>
						</ul>
					</div>
				</div>
			</div>
			<!-- /Page Header -->

			<div class="row">
				<div class="col-sm-12">
					<div class="card">
						<div class="card-body">
							<div class="table-responsive">
								<div class="table-responsive">
								<table class="datatable table table-hover table-center mb-0">
									<thead>
										<tr>
											<th>#</th>
											<th>service</th>
											<th>Salonist</th>
											<th>price</th>
											<th>start date</th>
											<th>end date</th>
											<th>status</th>
											<th class="text-right">Action</th>
										</tr>
									</thead>
									<tbody>
										{% for object in object_list %}
										<tr>
											<td>{{forloop.counter}}</td>
											<td>{{object.service.name}}</td>
											<td>{{object.salonist.get_full_name}}</td>
											<td>Ksh {{object.price|floatformat:2|intcomma}}</td>
											<td>{{object.date}}</td>
											<td>{{object.end_date}}</td>
											<td>
												{% if object.is_active and not object.ended %}
													Ongoing
												{% elif not object.is_active and object.ended %}
													Ended
												{% else %}
													Pending
												{% endif %}
											</td>
											<td class="text-right">
												<div class="table-action">
														<button class="btn btn-sm bg-info-light confirm" id="{{object.id}}"
																data-url="{% url 'finance:confirm_booking_payment' booking_id=object.id %}"
																data-slug="{{object.id}}">
															<i class="fe fe-check"></i> Approve
														</button>
<!--													<a href="#" class="btn btn-sm bg-primary-light">-->
<!--														<i class="fe fe-print"></i> Print-->
<!--													</a>-->
												</div>
											</td>
										</tr>
										{% endfor %}
									</tbody>
								</table>
							</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- /Page Wrapper -->

{% endblock content %}
{% include 'manager/includes/data-table-scripts.html' %}

manager/templates/manager/tables/products-list.html
{% extends 'manager/layout/base.html' %}
{% load static %}
{% block title %}Products List{% endblock title %}
{% include 'manager/includes/data-table-styles.html' %}
{% include 'manager/includes/header.html' %}
{% include 'manager/includes/sidebar.html' %}
{% block content %}

	<!-- Page Wrapper -->
	<div class="page-wrapper">
		<div class="content container-fluid">

			<!-- Page Header -->
			<div class="page-header">
				<div class="row">
					<div class="col-sm-12">
						<h3 class="page-title">List of Products <a href="{% url 'manager:products_pdf' %}" class="text-align-right" style="text-align: right;"> <i class="fe fe-print"> Generate pdf</i></a></h3>
						<ul class="breadcrumb">
							<li class="breadcrumb-item"><a href="{% url 'manager:index' %}">Dashboard</a></li>
							<li class="breadcrumb-item"><a href="javascript:(0);">Users</a></li>
							<li class="breadcrumb-item active">product</li>
						</ul>
					</div>
				</div>
			</div>
			<!-- /Page Header -->

			<div class="row">
				<div class="col-sm-12">
					<div class="card">
						<div class="card-body">
							<div class="table-responsive">
								<div class="table-responsive">
								<table class="datatable table table-hover table-center mb-0">
									<thead>
										<tr>
											<th>#</th>
											<th>product Name</th>
											<th>Description</th>
											<th>Quantity</th>
											<th>Price</th>
											<th>Date</th>
										</tr>
									</thead>
									<tbody>
										{% for object in object_list %}
										<tr>
											<td>{{forloop.counter}}</td>
											<td>
												<h2 class="table-avatar">
													<a href="#" class="avatar avatar-sm mr-2"><img class="avatar-img" src="{{object.image.url}}" alt="{{object.name}}"></a>
													<a href="#">{{object.name}}</a>
												</h2>
											</td>
											<td>{{object.description}}</td>
											<td>{{object.quantity}}</td>
											<td>{{object.price}}</td>
											<td>{{object.created}}</td>
										</tr>
										{% endfor %}
									</tbody>
								</table>
							</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
	<!-- /Page Wrapper -->

{% endblock content %}
{% include 'manager/includes/data-table-scripts.html' %}

manager/templates/manager/tables/salonists-list.html
{% extends 'manager/layout/base.html' %}
{% load static %}
{% block title %}Salonists List{% endblock title %}
{% include 'manager/includes/data-table-styles.html' %}
{% include 'manager/includes/header.html' %}
{% include 'manager/includes/sidebar.html' %}
{% block content %}

	<!-- Page Wrapper -->
	<div class="page-wrapper">
		<div class="content container-fluid">

			<!-- Page Header -->
			<div class="page-header">
				<div class="row">
					<div class="col-sm-12">
						<h3 class="page-title">List of Salonists <a href="{% url 'manager:salonists_pdf' %}" class="text-align-right" style="text-align: right;"> <i class="fe fe-print"> Generate pdf</i></a></h3>
						<ul class="breadcrumb">
							<li class="breadcrumb-item"><a href="{% url 'manager:index' %}">Dashboard</a></li>
							<li class="breadcrumb-item"><a href="javascript:(0);">Users</a></li>
							<li class="breadcrumb-item active">salonist</li>
						</ul>
					</div>
				</div>
			</div>
			<!-- /Page Header -->

			<div class="row">
				<div class="col-sm-12">
					<div class="card">
						<div class="card-body">
							<div class="table-responsive">
								<div class="table-responsive">
								<table class="datatable table table-hover table-center mb-0">
									<thead>
										<tr>
											<th>#</th>
											<th>salonist Name</th>
											<th>Email</th>
											<th>Phone</th>
											<th>Status</th>
											<th>Date</th>
										</tr>
									</thead>
									<tbody>
										{% for object in object_list %}
										<tr>
											<td>{{forloop.counter}}</td>
											<td>
												<h2 class="table-avatar">
													<a href="#" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="{{object.salonistprofile.image.url}}" alt="{{object.get_full_name}}"></a>
													<a href="#">{{object.get_full_name}}</a>
												</h2>
											</td>
											<td>{{object.email}}</td>
											<td>{{object.salonistprofile.phone_number}}</td>
											<td>
												{% if object.is_active and not object.is_archived and object.is_verified %}
												Active
												{% elif object.is_active and object.is_archived and object.is_verified %}
												Archived
												{% elif object.is_active and not object.is_archived and not object.is_verified %}
												Unverified
												{% endif %}
											</td>
											<td>{{object.created}}</td>
										</tr>
										{% endfor %}
									</tbody>
								</table>
							</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
	<!-- /Page Wrapper -->

{% endblock content %}
{% include 'manager/includes/data-table-scripts.html' %}