customer/urls.py
from django.urls import path

from user.decorators import customer_required
from . import views
from .receipts import OrderPaymentReceiptViewDownloadView

urlpatterns = [
    path('order-payment/<int:pk>/', customer_required(OrderPaymentReceiptViewDownloadView.as_view()),
         name="order_payment"),
    path('appointment/', customer_required(views.appointment), name="appointment"),
    path('service/<int:pk>/', customer_required(views.ServiceDetailView.as_view()), name="service-detail"),
    path('product/<slug>/', customer_required(views.ProductDetailView.as_view()), name="product-detail"),
    path('book_appointment/', customer_required(views.book_appointment), name="book_appointment"),
    path('generate_booking_receipt_pdf/<int:slug>/', customer_required(views.generate_booking_receipt_pdf),
         name="generate_booking_receipt_pdf"),
    path('generate_appointment_receipt_pdf/<int:slug>/', customer_required(views.generate_appointment_receipt_pdf),
         name="generate_appointment_receipt_pdf"),
    path('generate_order_receipt_pdf/<int:slug>/', customer_required(views.generate_order_receipt_pdf),
         name="generate_order_receipt_pdf"),
    path('generate_order_payment_receipt_pdf/<int:slug>/', customer_required(views.generate_order_payment_receipt_pdf),
         name="generate_order_payment_receipt_pdf"),
    path('generate_booking_payment_receipt_pdf/<int:slug>/', customer_required(views.booking_payment_receipt_pdf),
         name="generate_booking_payment_receipt_pdf"),
    path('book_hairstyle/<int:service_id>/', customer_required(views.book_hairstyle), name="book_hairstyle"),
    path('book_hairstyle/<int:service_id>/', customer_required(views.book_hairstyle), name="book_hairstyle"),
    path('booking_payment/<int:service_id>/', customer_required(views.booking_payment), name="booking_payment"),
    path('booking_checkout/', customer_required(views.booking_checkout), name="booking_checkout"),
    path('order_list/', customer_required(views.order_list), name="order_list"),
    path('checkout_pay/', customer_required(views.checkout_pay), name="checkout_pay"),
    path('checkout/', customer_required(views.checkout), name="checkout"),
    path('clear_cart/', customer_required(views.clear_cart), name="clear_cart"),
    path('increase_quantity/<slug>/', customer_required(views.increase_quantity), name="increase_quantity"),
    path('decrease_quantity/<slug>/', customer_required(views.decrease_quantity), name="decrease_quantity"),
    path('remove_from_cart/<slug>/', customer_required(views.remove_from_cart), name="remove_from_cart"),
    path('remove_from_wishlist/<slug>/', customer_required(views.remove_from_wishlist), name="remove_from_wishlist"),
    path('cart_list/', customer_required(views.cart_list), name="cart_list"),
    path('add_to_cart/<str:slug>/', customer_required(views.add_to_cart), name="add_to_cart"),
    path('add_to_wishlist/<str:slug>/', customer_required(views.add_to_wishlist), name="add_to_wishlist"),
    path('password_change/', customer_required(views.password_change), name="password_change"),
    path('change_password/', customer_required(views.change_password), name="change_password"),
    path('faq/', views.faq, name="faq"),
    path('wishlist_list/', customer_required(views.wishlist_list), name="wishlist_list"),
    path('profile/', customer_required(views.profile), name="profile"),
    path('profile_main/', customer_required(views.profile_main), name="profile_main"),
    path('add_booking/<int:slug>/', customer_required(views.add_booking), name="add_booking"),
    path('login/', views.login, name="login"),
    path('logout/', views.customer_logout, name="logout"),
    path('feedback_api/', customer_required(views.feedback_api), name="feedback_api"),
    path('feedback/', customer_required(views.feedback), name="feedback"),
    path('checkout/', customer_required(views.checkout), name="checkout"),
    # path('edit_billing/', views.edit_billing, name="edit_billing"),
    # path('favourites/', views.favourites, name="favourites"),
    # path('invoice_view/', views.invoice_view, name="invoice_view"),
    # path('invoices/', views.invoices, name="invoices"),
    # path('patient_profile/', views.patient_profile, name="patient_profile"),
    path('verify/<uidb64>/<token>/', views.VerifyEmail.as_view(), name="verify"),
    path('register/', views.CustomerSignUpView.as_view(), name="register"),
    # path('schedule_timings/', views.schedule_timings, name="schedule_timings"),
    path('apprenticeship_list/', customer_required(views.ApprenticeshipListView.as_view()), name="apprenticeship_list"),
    path('order_list/', customer_required(views.OrderListView.as_view()), name="order_list"),
    path('booking_list/', customer_required(views.BookingListView.as_view()), name="booking_list"),
    path('', customer_required(views.Home.as_view()), name="index"),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('search/', views.search, name="search"),
    path('term_condition/', views.term_condition, name="term_condition"),
    path('privacy-policy/', views.privacy_policy, name="privacy_policy"),
    path('about-us/', views.about_us, name="about-us"),
    path('salonists/', views.Salonists.as_view(), name="salonists"),
    path('', views.Home.as_view(), name="index"),
]

salon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name="user/forgot-password.html",
             html_email_template_name="user/email/password-reset.html",
             subject_template_name="user/email/password_reset_subject.txt",
         ),
         name="password_reset"),
    path('reset_password_done/',
         auth_views.PasswordResetDoneView.as_view(template_name="user/password-reset-done.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="user/auth-reset-password.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name="user/password-reset-complete.html"),
         name="password_reset_complete"),
    # ============================== Password Reset urls end ===========================================
    # third party app
    # path('mpesa/', include('mpesa_api.core.urls', 'mpesa')),

    path('admin/', admin.site.urls),
    path('finance/', include(('finance.urls', 'finance'), namespace="finance")),
    path('manager/', include(('manager.urls', 'manager'), namespace="project_manager")),
    path('salonist/', include(('salonist.urls', 'salonist'), namespace="salonist")),
    path('customer/', include(('customer.urls', 'customer'), namespace="customer")),
    path('trainee/', include(('trainee.urls', 'trainee'), namespace="trainee")),
    path('shipment/', include(('shipment.urls', 'shipment'), namespace="shipment")),
    path('stock/', include(('stock.urls', 'stock'), namespace="stock")),
    path('', include(('home.urls', 'home'), namespace="home")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'manager.views.error_404'
handler500 = 'manager.views.error_500'
handler403 = 'manager.views.error_403'
handler400 = 'manager.views.error_503'

customer/views.py
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ImproperlyConfigured
from django.core.mail import send_mail
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import NoReverseMatch, reverse
from django.utils.encoding import force_text, force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views import View
from django.views.generic import ListView, CreateView, DetailView
from weasyprint import HTML
from customer.forms import CustomerSignUpForm, CustomerFeedbackForm, CustomerProfileForm, CustomerForm
from customer.models import Customer, CustomerFeedback
from salonist.models import Salonist, SalonistProfile
from salonist.tokens import account_activation_token
from service.forms import BookingPaymentForm, AppointmentForm
from service.models import Service, Booking, Apprenticeship, BookingPayment, Appointment
from store.forms import OrderPaymentForm
from store.models import Order, Product, OrderItem, OrderPayment, Wishlist
from user.decorators import customer_required
from user.models import CustomUser
from utils.utils import generate_key


# from mpesa_api.core.mpesa import Mpesa


class Home(ListView):
    model = Service
    template_name = "customer/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customer = self.request.user.customer
        context['booking_transactions'] = BookingPayment.objects.filter(customer=customer)
        context['order_transactions'] = OrderPayment.objects.filter(customer=customer)
        print(f"These are payment orders {context['order_transactions']}")
        context['appointments'] = Appointment.objects.filter(customer=customer)
        context['bookings'] = Booking.objects.filter(customer=customer)
        order = Order.objects.filter(customer=customer)
        context['orders'] = order
        context['order'] = Order.objects.filter(customer=customer, completed=False).first()
        return context


class ApprenticeshipListView(ListView):
    model = Apprenticeship
    template_name = "customer/forms/apprenticeship.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = self.object_list.filter(is_active=True, closed=False, is_archived=False)
        return context


class BookingListView(ListView):
    model = Booking
    template_name = "customer/forms/booking.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customer = self.request.user.customer
        context['object'] = self.object_list.filter(customer=customer, is_active=False).first()
        context['order'] = Order.objects.filter(customer=customer, completed=False).first()
        return context


class OrderListView(ListView):
    model = Order
    template_name = "customer/forms/order.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customer = self.request.user.customer
        context['object_list'] = self.object_list.filter(customer=customer, is_active=True)
        return context


def login(request):
    if request.method == "POST":
        remember = request.POST.get('remember')
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if not remember == "remember-me":
            request.session.set_expiry(0)
        if user is not None:
            if not user.is_active and user.is_customer and not user.is_archived:
                if user.is_verified:
                    messages.info(request,
                                  "your email is verified, but your account is "
                                  "inactive. Check your mail for notification.")
                else:
                    messages.info(request,
                                  "your email is not verified, verify your email.")
            elif user.is_active and user.is_customer and not user.is_archived:
                if user.is_verified:
                    auth_login(request, user)
                    user = request.user.get_full_name
                    messages.success(request, f"Hi {user}, welcome to Ashley's Salon.")
                    try:
                        if 'add_to_cart' in request.GET.get('next', 'customer:index'):
                            return redirect('customer:index')
                        else:
                            return redirect(request.GET.get('next', 'customer:index'))
                    except (NoReverseMatch, ImproperlyConfigured):
                        return redirect("customer:index")
                else:
                    messages.info(request,
                                  "you've registered, but your email is not verified, verify your email and try again.")
            else:
                messages.info(request, f"Hi {user.get_full_name}, "
                                       f"you can't login here, this login page is for Customers only.")
                logout(request)
                try:
                    return redirect(request.GET.get('next', ''))
                except (NoReverseMatch, ImproperlyConfigured):
                    return redirect("customer:login")
        else:
            messages.info(request, "your email or password is incorrect. Please check.")
            try:
                return redirect(request.GET.get('next', ''))
            except (NoReverseMatch, ImproperlyConfigured):
                return redirect("customer:login")
    return render(request, 'customer/accounts/login.html')


class CustomerSignUpView(CreateView):
    form_class = CustomerSignUpForm
    template_name = "customer/accounts/register.html"

    def get_form_kwargs(self):
        kwargs = super(CustomerSignUpView, self).get_form_kwargs()
        return kwargs

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_invalid(self, form):
        context = {
            'info': "Please correct errors below",
            'form': form.errors,
        }
        return JsonResponse(context, status=200)

    def form_valid(self, form):
        name = form.instance.first_name
        last = form.instance.last_name
        username = form.instance.email
        username = username.lower()
        form.instance.email = username
        if '@gmail.com' in username:
            username = username.replace('@gmail.com', '')
        elif '@yahoo.com' in username:
            username = username.replace('@yahoo.com', '')
        elif '@hotmail.com' in username:
            username = username.replace('@hotmail.com', '')
        elif '@live.com' in username:
            username = username.replace('@live.com', '')
        elif '@msn.com' in username:
            username = username.replace('@msn.com', '')
        elif '@passport.com' in username:
            username = username.replace('@passport.com', '')
        elif '@outlook.com' in username:
            username = username.replace('@outlook.com', '')
        form.instance.username = username
        user = form.save(commit=False)
        user.is_active = True
        user.save()
        # current_site = get_current_site(self.request)
        # to_email = form.cleaned_data.get('email')
        # subject = f"Ashley's Salon Customer Email Verification."
        # msg_plain = render_to_string('customer/emails/email.txt', {'user_name': user.get_full_name, })
        # msg_html = render_to_string('customer/emails/account_activation_email.html', {
        #     'user': user,
        #     'domain': current_site.domain,
        #     'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        #     'token': account_activation_token.make_token(user),
        # })
        # send_mail(subject, msg_plain, "Ashley's Salon", [to_email], html_message=msg_html)
        data = {
            'status': True,
            'message': f"Hi {name} {last}, your account has been created successfully  wait for approval.",
            'redirect': reverse('customer:login')
        }
        return JsonResponse(data)


class VerifyEmail(View):

    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = Customer.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError):
            user = None
        data = {}
        if user is not None and account_activation_token.check_token(user, token):
            if user.is_verified:
                messages.info(request, "you've already confirmed your email.")
                data['message'] = "you've already confirmed your email."
            elif not user.is_verified:
                user.is_verified = True
                user.save()
                data['message'] = "You've successfully verified your email. use your email to login"
        else:
            data['message'] = 'The confirmation link was invalid, possibly because it has already been used.'
        return JsonResponse(data)


def log_out(request):
    logout(request)
    messages.info(request, f"You've logged out successfully.")
    return redirect('customer:index')


def profile(request):
    data = {}
    if request.method == "POST":
        p_form = CustomerProfileForm(request.POST, request.FILES, instance=request.user.customer.customerprofile)

customer/templates/customer/accounts/cart.html
{% extends 'customer/layouts/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
			
	<!-- Breadcrumb -->
	<div class="breadcrumb-bar">
		<div class="container-fluid">
			<div class="row align-items-center">
				<div class="col-md-12 col-12">
					<nav aria-label="breadcrumb" class="page-breadcrumb">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="{% url 'customer:index' %}">Home</a></li>
							<li class="breadcrumb-item active" aria-current="page">Dashboard</li>
						</ol>
					</nav>
					<h2 class="breadcrumb-title">Dashboard</h2>
				</div>
			</div>
		</div>
	</div>
	<!-- /Breadcrumb -->

	<!-- Page Content -->
	<div class="content">
		<div class="container-fluid">

			<div class="row">
				{% include 'customer/includes/sidebar.html' %}

				<div class="col-md-7 col-lg-8 col-xl-9">
					<div class="card">
						<div class="card-body pt-0">

							<!-- Tab Menu -->
							<nav class="user-tabs mb-4">
								<ul class="nav nav-tabs nav-tabs-bottom nav-justified">
									<li class="nav-item">
										<a class="nav-link active" href="#pat_appointments" data-toggle="tab">Cart</a>
									</li>
								</ul>
							</nav>
							<!-- /Tab Menu -->

							<!-- Tab Content -->
							<div class="tab-content pt-0">

								<!-- Appointment Tab -->
								<div id="pat_appointments" class="tab-pane fade show active">
									<div class="card card-table mb-0">
										<div class="card-body">
											<div class="table-responsive">
												<table class="table table-hover table-center mb-0">
													<thead>
														<tr>
															<th>Product</th>
															<th>Price</th>
															<th>Quantity</th>
															<th>Subtotal</th>
															<th>Action</th>
														</tr>
													</thead>
													<tbody>
														{% for object in object_list %}
														<tr>
															<td>
																<h2 class="table-avatar">
																	<a href="#" class="avatar avatar-sm mr-2">
																		<img class="avatar-img" src="{{object.product.image.url}}" alt="{{object.product.name}}">
																	</a>
																	<a href="#">{{object.product.name}} </a>
																</h2>
															</td>
															<td>Ksh {{object.get_price|floatformat:2|intcomma}}</td>
															<td>{{object.quantity}}</td>
															<td>Ksh {{object.get_total|floatformat:2|intcomma}}</td>
															<td><i class="fe fe-plus"></i></td>
														</tr>
														{% endfor %}
													</tbody>
												</table>
											</div>
										</div>
										<br/>
										<p><b>Total</b> Ksh.{{order.get_cart_total|floatformat:2|intcomma}}</p>
										<a href="{% url 'customer:checkout' %}" class="btn btn-primary">Proceed to checkout</a>
									</div>
								</div>
								<!-- /Cart Tab -->
							</div>
							<!-- Tab Content -->

						</div>
					</div>
				</div>
			</div>

		</div>

	</div>
	<!-- /Page Content -->

{% endblock content %}

customer/templates/customer/accounts/change-password.html
{% extends 'customer/layouts/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
			
	<!-- Breadcrumb -->
	<div class="breadcrumb-bar">
		<div class="container-fluid">
			<div class="row align-items-center">
				<div class="col-md-12 col-12">
					<nav aria-label="breadcrumb" class="page-breadcrumb">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="{% url 'customer:index' %}">Home</a></li>
							<li class="breadcrumb-item active" aria-current="page">change-password</li>
						</ol>
					</nav>
					<h2 class="breadcrumb-title">change-password</h2>
				</div>
			</div>
		</div>
	</div>
	<!-- /Breadcrumb -->

	<!-- Page Content -->
	<div class="content">
		<div class="container-fluid">

			<div class="row">
				{% include 'customer/includes/sidebar.html' %}

				<div class="col-md-7 col-lg-8 col-xl-9">
					<div class="card">
						<div class="card-body pt-0">

							<!-- Tab Menu -->
							<nav class="user-tabs mb-4">
								<ul class="nav nav-tabs nav-tabs-bottom nav-justified">
									<li class="nav-item">
										<a class="nav-link active" href="#edit-change-password" data-toggle="tab">Edit change-password</a>
									</li>
								</ul>
							</nav>
							<!-- /Tab Menu -->

							<!-- Tab Content -->
							<div class="tab-content pt-0">

								<!-- Appointment Tab -->
								<div id="edit-change-password" class="tab-pane fade show active">
									<div class="card card-table mb-0">
										<div class="card-body">
											<!-- Checkout Form -->
											<form action="{% url 'customer:change_password' %}" method="post" id="change-password">
												{% csrf_token %}
												<!-- Personal Information -->
												<div class="info-widget">
													<h4 class="card-title">Change Password</h4>
													<div class="row">
														<div class="col-md-6 col-sm-12">
															<div class="form-group card-label">
																<label>Old Password</label>
																{{form.old_password|add_class:"form-control"}}
															</div>
															<div class="text-danger" id="error-old_password">{{form.errors.old_password}}</div>
														</div>
														<div class="col-md-6 col-sm-12">
															<div class="form-group card-label">
																<label>New Password</label>
																{{form.new_password1|add_class:"form-control"}}
															</div>
															<div class="text-danger" id="error-new_password1">{{form.errors.new_password1}}</div>
														</div>
														<div class="col-md-6 col-sm-12">
															<div class="form-group card-label">
																<label>Confirm Password</label>
																{{form.new_password2|add_class:"form-control"}}
															</div>
															<div class="text-danger" id="error-new_password2">{{form.errors.new_password2}}</div>
														</div>
													</div>
												</div>
												<!-- /Personal Information -->
												<!-- Submit Section -->
												<div class="submit-section mt-4">
													<button type="submit" class="btn btn-primary submit-btn" id="id-change-password-btn">change password</button>
												</div>
												<!-- /Submit Section -->
											</form>
											<!-- /Checkout Form -->
										</div>
									</div>
								</div>
								<!-- /Appointment Tab -->
							</div>
							<!-- Tab Content -->

						</div>
					</div>
				</div>
			</div>

		</div>

	</div>
	<!-- /Page Content -->

{% endblock content %}
{% block scripts %}
<script src="{% static 'customer/assets/js/change-password.js' %}"></script>
{% endblock scripts %}

customer/templates/customer/accounts/feedback.html
{% extends 'customer/layouts/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
			
	<!-- Breadcrumb -->
	<div class="breadcrumb-bar">
		<div class="container-fluid">
			<div class="row align-items-center">
				<div class="col-md-12 col-12">
					<nav aria-label="breadcrumb" class="page-breadcrumb">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="{% url 'customer:index' %}">Home</a></li>
							<li class="breadcrumb-item active" aria-current="page">Feedback</li>
						</ol>
					</nav>
					<h2 class="breadcrumb-title">Feedback</h2>
				</div>
			</div>
		</div>
	</div>
	<!-- /Breadcrumb -->

	<!-- Page Content -->
	<div class="content">
		<div class="container-fluid">

			<div class="row">
				{% include 'customer/includes/sidebar.html' %}

				<div class="col-md-7 col-lg-8 col-xl-9">
					<div class="card">
						<div class="card-body pt-0">

							<!-- Tab Menu -->
							<nav class="user-tabs mb-4">
								<ul class="nav nav-tabs nav-tabs-bottom nav-justified">
									<li class="nav-item">
										<a class="nav-link active" href="#edit-change-password" data-toggle="tab">Send Feedback</a>
									</li>
								</ul>
							</nav>
							<!-- /Tab Menu -->

							<!-- Tab Content -->
							<div class="tab-content pt-0">

								<!-- Appointment Tab -->
								<div id="edit-change-password" class="tab-pane fade show active">
									<div class="card card-table mb-0">
										<div class="card-body">
											<!-- Checkout Form -->
											<form action="{% url 'customer:feedback_api' %}" method="post" id="feedback">
												{% csrf_token %}
												<!-- Personal Information -->
												<div class="info-widget">
													<h4 class="card-title">Feedback</h4>
													<div class="row">
														<div class="col-md-12 col-sm-12">
															<div class="form-group card-label">
																<label>Subject</label>
																{{form.subject|add_class:"form-control"}}
															</div>
															<div class="text-danger" id="error-subject">{{form.errors.subject}}</div>
														</div>
														<div class="col-md-12 col-sm-12">
															<div class="form-group card-label">
																<label>Message</label>
																{{form.message|add_class:"form-control"}}
															</div>
															<div class="text-danger" id="error-message">{{form.errors.message}}</div>
														</div>
													</div>
												</div>
												<!-- /Personal Information -->
												<!-- Submit Section -->
												<div class="submit-section mt-4">
													<button type="submit" class="btn btn-primary submit-btn" id="id-feedback-btn">Send</button>
												</div>
												<!-- /Submit Section -->
											</form>
											<!-- /Checkout Form -->
										</div>
									</div>
								</div>
								<!-- /Appointment Tab -->
							</div>
							<!-- Tab Content -->

						</div>
					</div>
				</div>
			</div>

		</div>

	</div>
	<!-- /Page Content -->

{% endblock content %}
{% block scripts %}s
<script src="{% static 'customer/assets/js/feedback.js' %}"></script>
{% endblock scripts %}

customer/templates/customer/accounts/register.html
{% extends 'customer/layouts/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
	<!-- Page Content -->
	<div class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-8 offset-md-2">
					<!-- Register Content -->
					<div class="account-content">
						<div class="row align-items-center justify-content-center">
							<div class="col-md-7 col-lg-6 login-left">
								<img src="{% static 'customer/assets/img/login-banner.png' %}" class="img-fluid" alt="Ashley's Salon Register">
							</div>
							<div class="col-md-12 col-lg-6 login-right">
								<div class="login-header">
									<h3>Customer Register <a href="{% url 'salonist:register' %}">Are you a Salonist?</a></h3>
								</div>
								<!-- Register Form -->
								<form action="{% url 'customer:register' %}" method="post" id="sign-up">
									{% csrf_token %}
									<div class="form-group form-focus">
										{{form.first_name|add_class:"form-control floating"}}
										<label class="focus-label">First Name</label>
									</div>
									<div class="text-danger" id="error-first_name">{{form.errors.first_name}}</div>
									<div class="form-group form-focus">
										{{form.last_name|add_class:"form-control floating"}}
										<label class="focus-label">Last Name</label>
									</div>
									<div class="text-danger" id="error-last_name">{{form.errors.last_name}}</div>
									<div class="form-group form-focus">
										{{form.email|add_class:"form-control floating"}}
										<label class="focus-label">email</label>
									</div>
									<div class="text-danger" id="error-email">{{form.errors.email}}</div>
									<div class="form-group form-focus">
										{{form.password1|add_class:"form-control floating"}}
										<label class="focus-label">password</label>
									</div>
									<div class="text-danger" id="error-password1">{{form.errors.password1}}</div>
									<div class="form-group form-focus">
										{{form.password2|add_class:"form-control floating"}}
										<label class="focus-label">Confirm password</label>
									</div>
									<div class="text-danger" id="error-password2">{{form.errors.password2}}</div>
									<div class="text-right">
										<a class="forgot-link" href="{% url 'customer:login' %}">Already have an account?</a>
									</div>
									<button class="btn btn-primary btn-block btn-lg login-btn" type="submit" id="sign-up-tn">Signup</button>
								</form>
								<!-- /Register Form -->
							</div>
						</div>
					</div>
					<!-- /Register Content -->
				</div>
			</div>

		</div>

	</div>
	<!-- /Page Content -->

{% endblock content %}
{% block scripts %}
<script src="{% static 'customer/assets/js/sign-up.js' %}"></script>
{% endblock scripts %}